### ISSUE TITLE
Integration of AfterBurner.fx with Spring-Boot

### ISSUE THREAD

**Issue by tommyziegler** [AdamBien/afterburner.fx#48]
Hello Adam,

I like your approach, with the automatic loading of FXML etc.

I started with the Spring-Boot with FX Integration Example from Thomas Darimont, a Spring Developer. 
See: https://github.com/thomasdarimont/spring-labs/tree/master/spring-boot-javafx
But we have the need in my project to separate our controller, view etc. by *.fxml and *.css files. Because then we can give out the layout tasks to our specialised UI/UX team.

But I completely dislike to write for every view, and subviews a own XML Loader. Your afterburner.fx project has solved this already in the FXMLView class. So I would love to combine it and make an example project out of it.

Could you please give me a hint how I can combine that!? Because I at the moment haven't found any way. And the examples which I saw only from you are the way over your own DI @Inject implemenetation.

Thanks in advanced

Tommy Ziegler

**Comment by tommyziegler** [comment]
I receive following stack trace when I insert your Followme... Classes and Resources:

Usage:
```
@Override public void start(Stage stage) {
            FollowmeView mainWindowView = new FollowmeView();
            Parent view = mainWindowView.getView();
            Scene scene = new Scene(view);
            stage.setScene(scene);
            stage.show();
}
```

Error:
```
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$9/1053512739.run(Unknown Source)
	... 1 more
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2438)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2413)
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:58)
	at com.airhacks.afterburner.views.FXMLView.init(FXMLView.java:51)
	at com.airhacks.afterburner.views.FXMLView.<init>(FXMLView.java:44)
	at net.steinberg.elicenser.download.gui.followme.FollowmeView.<init>(FollowmeView.java:29)
	at net.steinberg.elicenser.download.DownloaderManagerApp.start(DownloaderManagerApp.java:65)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$109/32732021.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$56/1339431330.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$58/52232842.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$57/625044122.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by AdamBien** [comment]
@tommyziegler I'm thinking about a pluggable support of injectors. Stay tuned.

**Comment by AdamBien** [comment]
Take a look at the recent release: http://www.adam-bien.com/roller/abien/entry/afterburner_fx_v1_7_0 You should be able to integrate with whatever framework you like without changing the code.
